name: lx/lx-auth

autoload:
  psr-4:
    lx\auth\:
      - ''
      - src

service:
  class: lx\auth\Service

  router:
    type: map
    routes:
      /: lx\auth\controller\OAuth2Controller::auth
      refresh: lx\auth\controller\OAuth2Controller::refresh

  modules: module
  models: model
  modelCrudAdapter: \lx\DbCrudAdapter
