name: lx/lx-auth

autoload:
  psr-4:
    lx\auth\:
      - ''
      - src

service:
  class: lx\auth\Service

  router:
    type: map
    routes:
      logout: {static: lx\auth\OAuth2AuthenticationGate::logOut}

  modules: module
  models: model
  modelCrudAdapter: \lx\DbCrudAdapter
